export const ERROR_CODES = {
  NOT_AUTHORIZED: 'USER_NOT_AUTHORIZED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  GOOGLE_USER_CANT_CHANGE_EMAIL: 'GOOGLE_USER_CANT_CHANGE_EMAIL',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',
  NO_VALID_FIELDS_TO_UPDATE: 'NO_VALID_FIELDS_TO_UPDATE',
} as const;
