export enum HTTP_STATUS  {
  OK =200,
  CREATED = 201,
  ACCEPTED = 202,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  CONFLICT = 409,
  INTERNAL_SERVER_ERROR = 500,
  GATEWAY_TIMEOUT = 504,
  TOO_MANY_REQUESTS = 429
};

export const SUCCESS_STATUS = {
  SUCCESS: true,
  FAILURE: false,
} as const;